In [1]:
import torch

In [14]:
input_ids = torch.tensor([2, 3, 5, 1])


In [3]:
input_ids

tensor([2, 3, 5, 1])

In [4]:
vocab_size = 6
output_dim = 3

In [5]:
torch.manual_seed(123)

In [6]:
embedding_layer = torch.nn.Embedding(vocab_size , output_dim)

In [12]:
print(embedding_layer(input_ids))

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)


tensor([3])